POST http://localhost:8081/api/token
Content-Type: application/json

{
  "userId": "amit123"
}

### Sync Stream User
POST http://localhost:8081/api/sync-user
Content-Type: application/json

{
  "userId": "amit123",
  "name": "Amit Kumar",
  "image": "https://i.pravatar.cc/150?img=3"
}

### Missing userId test
POST http://localhost:8081/api/sync-user
Content-Type: application/json

{
  "name": "Test"
}